# Generated by Django 4.1.2 on 2022-12-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0002_alter_item_category_alter_item_price_currentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUser',
        ),
    ]
